## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/blog/*"
  to = "https://rare-blog.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/blog/:article"
  to = "https://rare-blog.netlify.app/blog/:article"
  status = 200
